katdal/concatdata.py, katdal/dataset.py, katdal/h5datav1.py, katdal/h5datav2.py, katdal/h5datav3.py, scripts/h5toms.py, scripts/spectrogram_plot_example.py
The main reason for this PR is to support the latest MeerKAT HDF5
files with proper weights. This also allows h5toms to work with these
files (currently broken).
In the process some long-standing warts have been removed in
the vis / weights / flags API. All three attributes are now properties,
where weights and flags used to be methods to allow selection.
The selection is now done via the usual select() call. Flags and
weights have also been properly extended to all file formats.
The `squeeze` parameter on v2 and v3 datasets has been renamed
to `keepdims` to match the corresponding concept in NumPy (and it
now has the opposite sense). Its default behaviour also changed,
so that singleton dimensions are now discarded where indexed away
by default. Use `keepdims=True` to obtain the old …
=> Support weights in file and improve vis / weights / flags API

katdal/dataset.py, katdal/h5datav3.py
This is a step towards answering the age-old question "What is the centre frequency?".
The subarray band sensor is the most reliable indicator of the selected band as it matches the actual receivers and digitisers in use. Use that instead of the flakey AP indexer positions. Once we know the band, use that to figure out the centre frequency, which is correct for wideband modes.
The current supported receivers are:
- 'L': the standard 'l' band
- 'Ku': the only 'x' band so far, frequency derived from mixer sensor
- 'UHF': the only 'u' band so far, a hacked / custom version with an L-band digitiser and flipped spectrum
When the real 'x' and 'u' finally arrive we will deal with the disambiguation (serial numbers should suffice).
The Ku mixer sensor was accidentally dropped from AR1 and hence …
=> Support multiple receivers

katdal/averager.py, katdal/ms_extra.py, scripts/h5toms.py
Previously when handling a scan, h5toms would iterate over antenna pairs, handling all time, frequency and polarisation data for the associated baseline. This meant that data would be written to the Measurement Set in baseline ordering, rather than the more natural time ordering.
This commit modifies h5toms.py to iterate over chunks of time within a scan, thereby ordering
the MS by time. The time chunk size is chosen as a multiple of the time dump average.
=> Order dumps by time in h5toms

katdal/h5datav3.py
Two things changed in the new cam2telstate world:
- The sub sensors become telstate attributes as they should be
(previously these were flip-flopping between attrs and sensors)
- Like sensors their values are stored as pickles instead of str()s
This lets katdal deal with the new reality, specifically getting
a decent band value from the sub_band sensor to get the centre
frequency right.
=> Fix band selection after intro of cam2telstate

scripts/h5toms.py
Previously, an MS name was inferred from output-ms, similar to the case
where the MS name was inferred from the first hdf5 filename. This has
been changed to instead just use the raw output-ms string for creating
the MS string. By doing so, programs which depend on h5toms can reliably
know what the output MS will be.
=> Use raw output-ms option for MS name

scripts/h5toms.py
https://github.com/ska-sa/katdal/pull/64 modified h5toms to output visibility data in time ordered format. The optional creation of MODEL_DATA and CORRECTED_DATA columns was not modified to handle this new ordering, leading to table conformance errors caused by incorrectly shaped arrays.
This commit moves the creation MODEL_DATA and CORRECTED_DATA forward in the script to the point where the shape of vis_data has been reshaped into the expected (ntime\*nbl, nchan, npol) ordering, instead of the previous location where the shape of vis_data was (ntime, nchan, nbl\*npol).
=> Correct creation of model and corrected data

katdal/dataset.py
This fixes places in DataSet that would crash if the list of antennas
(or correlation products) is empty. The last place affects printing
of the data set and the rest are extraction of sensor values that
should be empty arrays.
=> Don't crash if there are no ants or corr products

katdal/h5datav3.py
RTS did not have the subarray band attribute / sensor before 2016-07-21.
It only had the AP indexer position per antenna. In this case guess the
receiver band as the most common valid indexer position amongst all
antennas in the subarray.
This is not very reliable as the indexer sensors are frequently invalid
and receivers may also be installed in the "wrong" indexer position.
Nevertheless try one's best and warn the user of the dangers, thereby
avoiding the user having to override the band for all old RTS files.
This addresses JIRA ticket [AR-276](https://skaafrica.atlassian.net/browse/AR-276).
=> Try to autodetect band on old RTS too

NEWS.rst, scripts/h5toms.py
Raise an exception if no usable data was found in HDF5 file. This is
typically because there were no tracks, no radec targets or a dud
reference antenna. Previously the script sauntered on and finally
crashed when attempting to use the then undefined `out_freqs`,
leading to much head-scratching.
Also do some flake8 cleanup and prepare for 0.7.1 on PyPI.
=> Let h5toms exit early if no data found

katdal/h5datav3.py
Since [MRTS-373](https://skaafrica.atlassian.net/browse/MRTS-373) the SDP ingest can select a subset of channels to avoid huge data files for RTS holography.
The problem is that katdal checks the actual number of channels against CBF's idea and crashes on a mismatch. Soften this to a warning instead and invalidate the centre frequency for now (we don't have a nice way to get the output channel range except for digging around in telstate).
Tested on 1487169336.h5 - attaching the result...
=> Don't crash if CBF reports a different number of channels to the data shape

katdal/__init__.py
When ipdb is running, _ip ends up being a boolean rather than a handle
to IPython. Calling set_hook thus crashes.
=> Make katdal work with ipdb

scripts/h5toms.py
Changes to allow h5toms to deal with single polarisation datasets by default.
I've removed the --HH and --VV options from h5toms.py. These previously would fake a Stokes I dataset using just a single pol, making CASA very unhappy as it looks for receptors that correspond to polarisations when it applies calibration models.
Instead I have now added a '--pols-to-use' option so that the user can specify which polarisations from the input h5 file that want in a (now correctly labelled) MS. The default behaviour is to look for any single pols in the input data and use these for the output (HH,VV if both are present or only one of these if that is all that is available).
I've added a bit of checking to make sure that --pols-to-use corresponds to pols that are available in the input file, and to …
=> Single pol

katdal/dataset.py, katdal/h5datav1.py, katdal/h5datav2.py, katdal/h5datav3.py, scripts/h5toms.py
There are two major changes:
1. When the spectral window uses lower sideband, conjugate the
visibilities on load, because the correlator/ingest do not correct for
it. This brings all data to the MeerKAT sign convention for
visibility phase. For v1 and v2 it's hardcoded (since they hardcode for
lower sideband), while for v3 it is dependent on the band.
2. Change the sign of UVW coordinates to match the CASA convention.
For MeerKAT the second change will make images made via h5toms come out
the right way up. For KAT-7 the two changes will cancel out when
imaging, although the sign conventions will now match MeerKAT.
Fixes SR-811.
=> Fix upside-down MeerKAT images

katdal/__init__.py, katdal/averager.py, katdal/categorical.py, katdal/concatdata.py, katdal/dataset.py, katdal/h5datav1.py, katdal/h5datav2.py, katdal/h5datav3.py, katdal/lazy_indexer.py, katdal/sensordata.py
This introduces the ```TelstateSensorData``` class which wraps raw (uninterpolated) sensor data stored in a ```TelescopeState``` object. The existing class with the same name is renamed to ```H5TelstateSensorData``` to highlight that it is wrapping telstate stored in HDF5 as opposed to the live database.
In the process, clarify the ```SensorData``` API, add the ```ComparableArrayWrapper``` class to support object-valued sensors like "cal_product_B" and clean up ```dtype``` support. This also required quite a bit of tinkering with ```CategoricalData``` and concatenated versions of these classes.
=> Access sensor data in a TelescopeState object

Jenkinsfile, katdal/categorical.py, katdal/test/test_categorical.py, requirements.txt, setup.py, test-requirements.txt
Rework the ```sensor_to_categorical``` function in response to the popularity of longer dump periods (e.g. 8 seconds) on MeerKAT. The existing function works OK if the dumps are shorter than the typical dish activities like tracks and slews. With 8-second dumps there is the  roblem that short slews (as found in e.g. interferometric pointing) may start and end within a single dump. This mini-slew is then filtered out by the dump -> event parser, resulting in a single track containing multiple pointings.
The new version of the function associates an entire dump with a greedy event, even if there is only a whiff of that event within the dump. Any non-greedy events at the end of such a dump is carried over to the next dump in this scenario. This logic is split out to its own function …
=> Improve dump to event parsing (and introduce unit tests)

katdal/categorical.py, katdal/sensordata.py
This addresses three issues:
- Revert the output of categorical sensors to be ndarrays as opposed to lists when `select=True`. This restores many use cases of noise diode sensors in standard reduction scripts.
- Fix katdal to work with NumPy 1.13. It is now a definite error if a boolean advanced index differs in length from the array it indexes. The main culprit is `CategoricalData` which applied the same index to `indices` and `events` attributes even though the latter is one longer than the former. This is JIRA ticket [SR-877](https://skaafrica.atlassian.net/browse/SR-877).
- Remove a NumPy FutureWarning which has no effect except being irritating. This points out that future interpretations of `array(a) == array(b)` for objects will not involve identity and that is the way we want it …
=> Revert sensor output to be arrays and fix SR-877

katdal/categorical.py, katdal/test/test_categorical.py
The `_single_event_per_dump` filter is supposed to mutate the events array to simplify the process of pushing forward displaced events. Unfortunately the code in `sensor_to_categorical` passed it a copy of `events`, which defeats the whole purpose of the mutation.
Pass in the real `events`, slap on more warnings about the mutation and even add a unit test to verify the finicky sensor->categorical conversion.
=> Fix categorical sensor parser

katdal/h5datav3.py
The new 'load_scan' receptor activity currently maps to the default 'stop' which is not very helpful. Rather map it to 'scan' as there is little chance of confusion with the standard linear scan and they are philosophically the same anyway (intended motion relative to a target).
=> Support load_scan

katdal/h5datav3.py, katdal/sensordata.py
The latest noise diode sensors have the band identifier as part of their name. For example, the old L-band `dig_noise_diode` is now `dig_l_band_noise_diode`. This caters for the different origins of the sensors as not all digitisers are served by the MeerKAT DMC.
Modify the main alias `nd_coupler` manually if a new-style noise diode sensor was found (else remain with the default 'dig_noise_diode'). This should have been a proper sensor alias, but that machinery can only change suffixes and we need to move from `TelescopeState` to `Antennas` as well.
Also ensure that all sensors ending in `noise_diode` are interpreted correctly. And allow aliases to be added to the `SensorCache` after construction for posterity.
This addresses JIRA ticket …
=> Load new-style noise diode sensors

katdal/h5datav3.py
This is to handle the new attributes written by ingest
(ska-sa/katsdpingest#194) and filewriter (ska-sa/katsdpdata#71), which
allow for
- The file to contain either the continuum or spectral L0 stream
(disambiguated by an HDF5 attribute on the /Data group);
- The file to contain only a subset of channels, and thus have separate
n_chans, bandwidth, centre frequency to the CBF.
An area that will need some review is the precedence of the different
ways of determining centre frequency. Currently I've made it trust the
SDP-written value (e.g. sdp_l0_center_freq) over anything else, because
values determined from the band don't take account of channel subsetting
in ingest. However, that in turn means trusting the CAM centre
frequency, which is probably not correct for Ku band. I propose that …
=> Handle output L0 stream attributes

katdal/h5datav3.py, katdal/visdatav4.py
The underlying sensor has changed from the raw "rsc_rxl_serial_number" to "rx_serial_number". Since August, cam2telstate picks the appropriate sensor based on the subarray band, crucially renames it and then ignores the rest. This behaviour has now also been rolled out to RTS, hence the fix.
=> Fix receiver serial numbers

NEWS.rst, katdal/ms_extra.py, scripts/h5toms.py
Previously, h5toms created variable length data columns when creating a MeasurementSet. Catering for this variability means the MS's are not performant. This PR 
1. Modifies h5toms to use python-casacore's upcoming functionality for creating canonical Measurement Set's. This removes the need to maintain table definitions for the MS within katdal.
2. Modfies h5toms to define fixed shape columns for `DATA`, `MODEL_DATA`, `CORRECTED_DATA`, `FLAG`, `FLAG_CATEGORY`, `IMAGING_WEIGHTS`, `WEIGHTS` and `SIGMA`, as well as the original hypercolumn definitions that were bases on these columns.
Depends on https://github.com/casacore/python-casacore/pull/72.
=> Use python-casacore's pending MeasurementSet creation functionality for creating Fixed Shape columns

katdal/concatdata.py, katdal/dataset.py, katdal/h5datav3.py
On pre-telstate v3 files, the `_get_telstate_attr()` helper function crashes when it looks for improved versions of the dump period attribute in the sensor cache. The problem is that the sensor cache
does not exist this early on in the metadata parsing... Fall back to the default obtained from the TelescopeModel on this exception.
=> Fix opening of older v3 files

katdal/ms_extra.py, setup.py
python-casacore 2.2.1 is required for creating Measurement Sets. Raise an informative ImportError if the required version is not installed, rather than failing due to missing functionality.
=> Require python-casacore 2.2.1 when importing

katdal/h5datav3.py
The main fix is to avoid looking into the CBF stream for the L0 centre frequency as it is unreliable for this purpose.
Refactor the attribute search by introducing a helper method which raises an exception if the attribute was found (and not vice versa!). This makes it easy to chain a series of search locations with decreasing priority. It also logs the results of the search, for debug purposes.
This closes #108 and should enhance the debugging of similar issues in the future.
Tested on a very small menagerie of files.
=> Improve stream attribute search

katdal/concatdata.py, katdal/sensordata.py
This removes a FutureWarning issued by numpy 1.14 and later. It is
no longer cool to be vague about the second argument to `np.issubdtype`.
It currently does some unexpected type conversions internally that
will go away eventually. If we are checking for a general floating-point
type, use np.floating instead of np.float (which is np.float64).
The same goes for np.integer, np.string_ and np.bool_ (which also have
sub-types). In those cases, also convert the default value to the
correct type (i.e. np.nan != np.float32(np.nan)).
=> Be more specific when comparing numpy dtypes

katdal/chunkstore.py, katdal/chunkstore_dict.py, katdal/chunkstore_npy.py, katdal/chunkstore_rados.py, katdal/chunkstore_s3.py, katdal/test/test_chunkstore.py, katdal/test/test_chunkstore_npy.py, katdal/test/test_chunkstore_rados.py, katdal/test/test_chunkstore_s3.py
These smaller changes pave the way for dask:
- Improve RADOS error report if chunk is too big (unrelated)
- Rename `get` to `get_chunk` etc (there will soon be a `get_dask_array`)
- Switch to class-level fixtures in the tests (we need to add `test_put_and_get_dask_array`)
- Override botocore settings (unrelated, speeds up tests a lot)
=> SR919: Prepare for dask

katdal/h5datav3.py, katdal/visdatav4.py
Since 2017-11-15 RTS renamed the `rsc_rxl_serial_number` sensor to
`rx_serial_number` (i.e. dropping the band label). AR1 / MKAT would
have done this too, but stopped short at the last minute (see
katsdpingest PR #189). Since 2018-01-16 the MKAT files no longer have
the corresponding TelescopeModel sensor to fall back on. To fix this,
first look for the original sensor name in TelescopeState.
The `dig_l_band_noise_diode` sensor (renamed as `dig_noise_diode`)
luckily don't suffer from the same issue, as there the renamed sensor
matches the old name and the full name is already looked up first in
TelescopeState.
This closes issue #114.
=> Look for unrenamed RX serial number sensor first

katdal/chunkstore.py, katdal/test/test_chunkstore.py, requirements.txt, setup.py
Add `get_dask_array` method that combines all the chunks associated with an array into a single dask Array and loads the associated data only on compute(). The corresponding `put_dask_array` method stores the chunks of a dask array in the store and returns a results array that also suppresses any exceptions (for inspection by the caller).
The supporting `generate_chunks` function provides a standard way to split an array into roughly equal-sized chunks. Dask is only a test requirement for now - wait until we have a fully integrated v4 loader to make it a main requirement.
=> Add dask support to ChunkStore

katdal/chunkstore.py, katdal/chunkstore_dict.py, katdal/chunkstore_npy.py, katdal/chunkstore_rados.py, katdal/chunkstore_s3.py, katdal/test/test_chunkstore.py
This does a basic check to see if a given chunk (or array) is present in the store, with the appropriate size (and dtype if supported), using the new `has_chunk` and `has_dask_array` methods. The idea is that it should be (much) faster than the default `get_chunk`, otherwise there is very little point...
I'm really adding this as a debugging tool, so it is not very optimised. Especially multi-chunk checking on e.g. S3 can still be sped up a lot.
=> Check presence of chunks in store

katdal/chunkstore_rados.py, katdal/dataset.py, katdal/datasources.py, katdal/lazy_indexer.py, katdal/visdatav4.py
This brings the V4 formatter up to speed (note that this PR piggy-backs on #118). The main improvements are:
- Use telstate views
- Add vis / flags / weights indexers
An RDB file can currently be opened like this:
```Python
from katdal.datasources import open_data_source
from katdal.visdatav4 import VisibilityDataV4
ds = open_data_source('dump.20180207-0002.rdb?capture_block_id=20180207-0002-1517994195&stream_name=sdp_l0')
f = VisibilityDataV4(ds)
f.select(dumps=slice(0,10), ants='m003,m000,m017', channels=slice(0,1000))
f.vis[:].shape
(10, 1000, 24)
```
Output:
```
===============================================================================
Name: file:///dump.20180207-0002.rdb?capture_block_id=20180207-0002-1517994195&stream_name=sdp_l0 | …
```
=> SR919: V4 formatter update

katdal/dataset.py, katdal/datasources.py
The default TelstateDataSource constructor now takes a telstate that
already has views associated with the capture block and stream. This
requires the reintroduction of `chunk_name` to figure out the chunk
store name of the dataset (as `capture_stream` is now implicit again).
This is the intended way to open pipeline data.
When constructing telstate from an URL with no prior views, detect
the capture block ID and stream name. Crash if there are none and warn
if there are more than one. Then prepare the telstate with the relevant
views before passing on to the usual constructor.
=> Autodetect program block ID and stream name

katdal/__init__.py, katdal/datasources.py, katdal/visdatav4.py
Synchronise v4 format with new `CaptureSession` as we now have `obs_params` as an attribute and `sdp_capture_block_id` needs to lose its unicodeness.
Then plumb all the goodness straight into `katdal.open()` and declare success!
=> SR-1052: katdal.open() a V4 file

katdal/datasources.py, katdal/visdatav4.py
- Allow chunk store to be overridden (opens NPY files during testing instead of S3)
- Fix mxxx_observer which is now an attribute
- Shorten sensor names by discarding the most relevant prefix from the telstate key
=> Various v4 mop-up operations

katdal/datasources.py
Rather rely on the top-level attributes introduced in RDB files, viz `capture_block_id`, `stream_name` and `stream_type`. If any of them are missing, insist on a manual override. Also bail if the stream type is not "sdp.vis".
There is also no more need for `sdp_config` and `sdp_capture_block_id` in the "lite" RDB files.
=>  Remove CBID / stream autodetection

katdal/chunkstore_npy.py, katdal/datasources.py
This writes to a temporary filename first (ending in '.writing.npy')
before renaming it to the final '.npy' file after the file has been
closed. This ensures that other processes waiting for the file (like
the vis trawler) knows when it is safe to pick it up.
Also fix a grammar bug.
=> Make writing an NPY file atomic

katdal/chunkstore_s3.py, katdal/datasources.py
For RDB files this first attempts to locate an `NpyFileChunkStore` in an adjacent directory named after the capture stream, as is typically produced by `vis_writer` and other tools. Failing this, it falls back to the S3 gateway suggested by telstate. Another fail here is treated as an error (as this is typically due to authentication or network connection errors that the user wants to know about). The redis server option only attempts the S3 option, since there is no file access.
If the user really wants no chunk store it can be specified as `None`, which is useful for metadata extraction.
This allows the dream of `katdal.open('whatever')`, at least for RDB files :-)
=> Improve autodetection of chunk store

katdal/datasources.py
TelstateDataStore.from_url('file:///...', store) would ignore the
provided store, and use the s3_endpoint_url from the RDB file
regardless.
The logic is changed now so that chunk_store is only overridden if it is
given as 'auto'.
=> Fix explicit override of a chunk store with file URL

katdal/h5datav3.py, katdal/sensordata.py, scripts/h5toms.py, scripts/objtoms.py
This allows pickles containing binary (rather than ASCII) data to be
loaded. See SR-675.
=> Decode binary pickles from HDF5 v3 files

katdal/chunkstore_s3.py, requirements.txt, setup.py
My authenticated katdal version. It is not really necessary to include the import as part of katdal itself. Technically simply importing katadpauth.auth_botocore in any script will patch anything in it using botocore to use my authentication. I think it may be a good idea to create a small script (auth_katdal or something) which simply imports katdal and katsdpauth.auth_botocore which will allow us to not perform the pull in your code.
This current version will not ask you to log in unless you are trying to access a protected resource. If you are on a whitelisted machine, katdal will simply run as it currently does, otherwise you will be prompted to log in.
=> Authenticated katdal

katdal/h5datav3.py, katdal/sensordata.py
This is needed to put variable-length pickles into a sensor HDF5
dataset.
The no_unpickle functionality is moved into pickle_loads because the
test 'value in no_unpickle' spews a deprecation warning if value is an
ndarray - so we only want to do it on (legacy) strings.
=> Handle binary pickles in sensors encoded as array of uint8

katdal/lazy_indexer.py, katdal/test/test_lazy_indexer.py
Fixes SR-1166. This makes loading all the data from a file twice as fast
and much less CPU-intensive.
=> Avoid using dask advanced indexing in common cases

README.rst, katdal/__init__.py, katdal/chunkstore_s3.py, katdal/datasources.py, katdal/visdatav4.py, requirements.txt, scripts/mvftoms.py, setup.py
This is a first pass to prepare for release:
- Improve timeouts and errors for S3
- Restore support for NumPy 1.11 / Ubuntu 16.04
- Speed up flag access
- Fix relative NPY store paths
- Update docs to refer to datasets and not files (MVF still has to happen)
- Quack by default in mvftoms
- Remove katsdpauth from requirements.txt for now
=> Clear up v4 niggles

scripts/mvftoms.py
My detection of the dataset being dask-like was flawed and was
incorrectly trying to use da.store on HDF5 data.
=> Fix mvftoms for v3 files

katdal/test/test_chunkstore_s3.py
The new Docker version on sdp-jenkins seems to map 'localhost' to an IPv6 address, even when IPv6 is disabled. This prevents connection to the FakeS3 server and fails the `S3ChunkStore` tests.
Rather use the explicit '127.0.0.1'. Also suppress the FakeS3 stdout for cleaner test reports when done on the command line.
=> Fix S3 unit tests again

katdal/chunkstore.py, katdal/chunkstore_s3.py, katdal/datasources.py, katdal/test/test_chunkstore.py, katdal/test/test_chunkstore_dict.py, katdal/test/test_datasources.py, katdal/test/test_lazy_indexer.py
All missing chunks (i.e. chunks raising `ChunkNotFound` in the chunk store) are now replaced by zeros of the appropriate shape and dtype. In addition, missing chunks in the `correlator_data`, `weights` and `weights_channel` (but not `flags`...) arrays will get flagged as `data_lost`.
In the process, add unit tests for `ChunkStoreVisFlagsWeights`, including the ability to make fake datasets in the chunk store.
The last niggle is to replace the explicit flag value of 8 with `data_lost` but that will come in a separate PR that will rearrange all the flag info.
=> Flag and zero missing chunks

NEWS.rst, katdal/chunkstore_dict.py, katdal/chunkstore_npy.py, katdal/chunkstore_rados.py, katdal/chunkstore_s3.py
Make `has_chunk` as lightweight as possible. It now only checks the
presence or absence of a chunk based on its name (i.e. it checks
whether an NPY file or S3 object exists). The chunk dtype and shape
will still be checked by `get_chunk` and result in a `BadChunk`
exception if wrong. There is no need to anticipate this in `has_chunk`.
This fixes NumPy 1.14 support, which modified the size of the NPY file
header by changing its padding (see numpy/numpy#8598). This made it
harder to predict the expected S3 object size (which was still being
produced by an older NumPy), so get rid of the check.
=> Fix NumPy 1.14 support by simplifying has_chunk

katdal/chunkstore.py, katdal/chunkstore_npy.py, katdal/chunkstore_s3.py, katdal/test/test_chunkstore.py
Since the flags now call `has_dask_array` on the rest of the arrays
in the dataset, it is time to optimise it. This feature can also be
used to check which chunks are present upon opening a dataset.
Some chunk store implementations allow an efficient enumeration of
all chunks associated with an array. We are only interested in the
presence or absence of a chunk and nothing more. For example, the
`NpyFileChunkStore` can `os.listdir` the array subdirectory to get
a list of all the relevant NPY files, while the `S3ChunkStore` can
send a `list_objects_v2` request with the appropriate bucket and prefix
to get a list of associated keys (via pagination).
If this efficient `list_chunk_ids` method is available, use it within
`has_dask_array`, otherwise fall back to a series of `has_chunk` calls. …
=> Optimise has_dask_array

katdal/chunkstore_s3.py, katdal/test/test_chunkstore_s3.py, setup.py, test-requirements.txt
On initialisation of S3ChunkStore a connection is made to the S3
endpoint URL to check that it is up. While useful, this can lead to
interminable delays while doing DNS lookups for `archive-gw-1.kat.ac.za`
(at least from my admittedly pathological home setup via sshuttle).
The worst part is that DNS lookup via `socket.gethostbyname()` ignores
the usual timeout mechanisms. Therefore introduce a hard cutoff by
running the blocking initialisation code in a separate thread. The
constructed store (or an exception) is returned via a queue. This
smacks of `concurrent.futures` but avoids adding yet another dependency
on Python 2 just for this (revisit when Python 3 only...).
Test that the initialisation happens within the expected time period.
=> Enforce timeout when constructing S3 chunk store

katdal/__init__.py, katdal/chunkstore_s3.py, katdal/datasources.py, katdal/visdatav4.py, scripts/mvftoms.py
This is a small platter of fixes to make katdal more robust:
- Fix a fatal bug in mvftoms (see [COMM-318](https://skaafrica.atlassian.net/browse/COMM-318))
- Map a requests ReadTimeout to StoreUnavailable
- Retry S3 connections twice, to cater for network glitches
- Open the RDB metadata even if the chunk store is missing or inaccessible
- Warn when timestamps and/or data is missing (but continue opening what you have)
- Allow simple overrides of key parameters via kwargs to `katdal.open` as well as query strings in the original URL
=> Robustify and add metadata fallback

katdal/visdatav4.py
The compscan labels have always been exposed via the 'Observation/label'
sensor, which crucially allows repeats. In v4 land this sensor is
initialised from the 'obs_label' telstate sensor, but that sensor is
extracted without the same sensor props. Add the relevant props.
I've toyed with the idea of getting obs_label props directly from the
existing Observation/label props, but I think there is no more need for
the `transform=str` bit, for one, so rather be explicit.
=> Fix sensor props for v4 observation labels

katdal/lazy_indexer.py
This works around https://github.com/dask/dask/issues/3595. Note that it
is potentially slower (I haven't measured it), but I'll take slower over
not eating all the memory in my machine.
=> Use da.store to a freshly allocated array, instead of da.compute

katdal/lazy_indexer.py, scripts/mvftoms.py
The implementation of the dask array optimizer is tuned for cases where
most of the graph is retained, which doesn't match the use for lazy
indexing to load small pieces at a time.
=> Optimise DaskLazyIndexer for small reads from large files

katdal/chunkstore.py, katdal/datasources.py, katdal/test/test_chunkstore.py, katdal/test/test_datasources.py
Instead of synthesizing a sequence of masks (which are mostly zero), it
looks at the list of missing chunks, and computes the pieces of each
flag chunk that need the mask applied. A single map_blocks is then used
to apply the mask only where needed. This gives a 10x speedup.
=> Speed up flagging of lost data

katdal/chunkstore.py, katdal/chunkstore_dict.py, katdal/chunkstore_npy.py, katdal/chunkstore_rados.py, katdal/chunkstore_s3.py, katdal/test/test_chunkstore.py, katdal/test/test_datasources.py, requirements.txt, setup.py
The token-based authentication authenticates with our JWT-based proxy.
This adds credential authentication using an access key and secret key.
It relies on botocore to generate the signatures, which is added as an
optional dependency ("s3credentials").
Also adds a create_array method to ChunkStore, which should be used
before calling put_chunk or put_dask_array to ensure that the bucket
(S3ChunkStore) or directory (NpyFileChunkStore) is created, and that the
bucket policy allows public access if requested.
=> Support AWS-style authentication to S3ChunkStore

katdal/__init__.py, katdal/sensordata.py
Since IPython 5.0 (PR ipython/ipython#9289 specifically) the
customisation of dict key lookups has been considerably simplified by
adding a specific method (`_ipython_key_completions_`) to your object.
For the `SensorCache` it is not even necessary to add this method since
it is derived from the standard dict. Strip out all the old tab
completion machinery as a result.
Unfortunately the rest of the IPython machinery is still a bit clunky
and the default completions now include all known tokens with that
prefix, not only the ones returned by `_ipython_key_completions_`.
This can be fixed by monkeypatching IPython in one of its startup files
(ask the author).
=> Modernise tab completion

katdal/chunkstore.py, katdal/chunkstore_npy.py, katdal/chunkstore_s3.py, katdal/test/test_chunkstore.py, katdal/test/test_chunkstore_s3.py
This was being handled by katsdpdatawriter, but in a way that would only
work for NpyFileChunkStore. This will allow katsdpdatawriter's internals
to be chunk store agnostic.
It's not implemented for RadosChunkStore, because I don't have a
convenient way to test that. We should consider just deleting
RadosChunkStore since it's never used nor planned to be used.
=> Add mark_complete and is_complete to ChunkStore

katdal/chunkstore_s3.py, katdal/test/test_chunkstore_s3.py, requirements.txt, setup.py
- Require the latest version of minio (which has bug-fixes), otherwise skip test
- In the test proxy, sanitise HTTP headers that shouldn't be passed through a proxy
- Remove no-longer-needed contextlib.closing wrapping
- Fix unit tests on OS X
=> Improvements in S3 unit test

.gitignore, katdal/lazy_indexer.py, katdal/test/test_lazy_indexer.py
This prepares to prepare for applycal...
The DaskLazyIndexer is given a bit of a facelift, with explicit oindex semantics (see JIRA [SR-1323](https://skaafrica.atlassian.net/browse/SR-1323)) and a way to add transforms after instantiation.
=> Upgrade DaskLazyIndexer

katdal/chunkstore_s3.py
Writing the numpy array to a BytesIO and passing that BytesIO to
requests is very slow, possibly because httplib reads it 8KB at a time.
The new approach is a bit more fragile but is zero-copy if the input
array is C-contiguous.
=> Optimise S3ChunkStore.put_chunk

katdal/__init__.py, katdal/lazy_indexer.py, katdal/test/test_lazy_indexer.py, scripts/mvftoms.py
mvftowas was broken by #180, which took away the `dask_getitem` member
function and replaced it with a `_dask_getitem` free function. Fix by
renaming the free function to `dask_getitem`, importing it into the
top-level katdal namespace, and using it in mvftoms.
Closes #184.
=> Fix mvftoms after the oindex update

katdal/applycal.py, katdal/lazy_indexer.py, katdal/test/test_applycal.py, katdal/visdatav4.py, requirements.txt, setup.py
This is a first stab at the machinery of "Make L1". It only does `cal_product_K`, and only corrects visibilities.
I am looking for comments on the basic idea before forging ahead...
It is based on a set of per-input gain correction sensors, which is about the smallest thing one can cache that makes sense. The corrections are meant to be cleaned up and interpolated where needed.
The corrections are then applied per chunk via dask `map_blocks`, by obtaining the appropriate sensor values per chunk, expanding them to become per baseline, and applying them with a vis-weights-flags specific method.
=> Make L1 product (the scaffolding)

katdal/chunkstore_s3.py
While testing on my home machine, I ran into unit test failures because
code inside Python 3.6's httplib does
```
if not chunk:
```
and if chunk is an ndarray then raises ValueError.
Wrap it in a memoryview so that truthiness is more sensible. I haven't
measured the performance impact, but the initial development of the
_Multipart optimisation used a memoryview and performed acceptably
well.
=> Fix S3ChunkStore for Python 3.6

katdal/dataset.py, katdal/test/test_dataset.py
Can now compute a new spectral window with a (contiguous) subset of
channels or a new channelisation of the bandwidth.
Closes SR-1369.
=> Make SpectralWindow do channel juggling

katdal/datasources.py, katdal/lazy_indexer.py, katdal/test/test_datasources.py, requirements.txt, scripts/mvftoms.py, setup.py
If the telstate key 'need_weights_power_scale' is set on the L0 stream, the weights are divided by the product of the autocorrelation visibilities. This will be matched with changes to katsdpingest and katsdpdata to set this flag and remove the equivalent scaling done in ingest.
Relates to SR-1230.
=> Scale weights by autocorrelation power during read

katdal/applycal.py, katdal/test/test_applycal.py
The bandpass solutions are linearly interpolated from the cal frequencies onto the visibility frequencies, across any invalid channels with NaNs (unless all channels are bad). There is no
interpolation over time.
This still uses the complex interpolator introduced in ska-sa/katsdppipelines#117, but this will soon be reworked to operate on magnitude + unwrapped phase directly.
=> Make L1: bandpass

katdal/applycal.py, katdal/sensordata.py
There were two issues:
- TelstateSensorData has an internal cache, which was not locked.
- SensorCache.get mutates its internal structures (in the case of
virtual sensors, that includes the set of keys present), again
without a lock.
Remove the bandaid on get_cal_product which should no longer be needed.
=> Make the sensor cache safe for multiple readers

katdal/applycal.py, katdal/dataset.py, katdal/h5datav2.py, katdal/h5datav3.py, katdal/sensordata.py, katdal/test/test_applycal.py, katdal/test/test_dataset.py, katdal/visdatav4.py
Apply calibration corrections to weights and flags. The weights are divided by the magnitude squared of the corrections. The flags are set to True wherever the gains were invalid. This is
done after the flags are combined, on the boolean level (as opposed to the "raw" uint8 level). Ideally a new "cal_failure" flag type should be introduced instead, but that is left for a future PR.
Enable applycal upon opening a v4 data set, by listing the desired cal products to apply. This is disabled by default for now until the functionality has been thoroughly vetted.
There are still some issues with the final version running on real data, which seems to be due to the multi-threading introduced by the default dask scheduler. Adding a lock to `get_cal_product` seems to fix this, but I'm leaving that …
=> Make L1: apply to weights and flags and plumb it into v4

katdal/datasources.py, katdal/test/test_datasources.py
The `ChunkStoreVisFlagsWeights` class gains a `prefix` attribute
which corresponds to the S3 bucket name for the visibility data
(considered the main payload and therefore representative of the
data set). This aids the archive metadata extractor by removing the
need to scavenge around in `chunk_info`.
This addresses JIRA ticket SR-1401.
=> Expose S3 bucket name on data source

katdal/datasources.py
open_data_source() must not swallow DataSourceNotFound exception for URL's that don't have "file" protocol.
=> bugfix: open_data_source() swallowing an exception

katdal/h5datav3.py
If an attribute in an HDF5v3 data set is not found in the `attrs` section of the `TelescopeState group`, one should check the sensors as well.
When #196 introduced telstate-level decoding, UnpicklingErrors was replaced by DecodeErrors but unfortunately the KeyError in this except clause got lost in the process.
This addresses JIRA ticket SR-1503.
=> Fix attribute lookup regression on H5 files

katdal/chunkstore.py, katdal/chunkstore_npy.py, katdal/chunkstore_s3.py, katdal/test/test_chunkstore_npy.py
When true, writes the chunks with O_DIRECT option to bypass the OS
filesystem cache.
=> Add direct_write option to NpyFileChunkStore

katdal/datasources.py
Optionally don't include the l1-flags when opening the observation. This is useful when using the pipeline simulator to run on an mvf4 file, typically this is useful to debug problems with the pipeline. Switching off the l1 flags more faithfully represents the flags that would have been seen by the pipeline during the real observation.
=> Optionally 'switch off' l1-flags

katdal/datasources.py
It was broken by #209. Now instead of passing all kwargs to
DataSource.__init__, only pass upgrade_flags (plus what was passed
before).
Note that this means the telstate and chunk store init will no longer
see the upgrade_flags argument.
Fixes SR-1571.
=> Fix passing kwargs like capture_block_id in URLs

katdal/test/test_datasources.py
This is in preparation for SR-1330. It tests cases where the L1 flags
stream has a different number of dumps, giving 100% line coverage of
_upgrade_chunk_info.
=> Add more tests of _upgrade_flags

katdal/chunkstore.py
In previous dask versions it was automatically imported, but now needs
to be imported explicitly. It is also deprecated in dask 1.1, but that's
a problem for another day.
=> Add missing import of dask.sharedict

katdal/chunkstore.py, katdal/test/test_chunkstore.py
This will help with the spectral vis writer, allowing the number of
channels to be limited.
The algorithm was changed to determine an (integral) chunk shape, and then
divide everything into chunks of that shape (with smaller left-overs at
the end).
The behaviour changes slightly: when not using power_of_two, the chunks
are now all the same size except the last which is smaller (like with
power_of_two), rather than having chunks of size X+1 and X. This
simplifies the code, and I don't think !power_of_two is being used much
if at all any more.
=> Add max_dim_elements option to generate_chunks

katdal/visdatav4.py
This is a slight rework of the reference antenna machinery to fix
issues with DataSet.lst and a broken ConcatenatedDataSet.
Instead of leaving the `ref_ant` attribute empty in the default case,
explicitly set it to "array". This creates a fake antenna called "array"
with its own katpoint.Antenna object, target sensor and activity sensor.
The rest of the katdal sensor machinery in the base class can then
access the reference antenna properties (such as local sidereal time, or
LST) via the usual mechanisms. It also fixes the bug reported in
SR-1587. In the process, also set up target and activity sensor aliases
for the rest of the antennas to have a consistent view on these.
In the process, also fix a bug in the extraction of the array reference antenna
object, which ended up being just the …
=>  Rework reference antenna to fix LST and ConcatenatedDataSet

katdal/test/test_datasources.py
After katsdptelstate changed the default encoding to msgpack, the unit
test faking a chunk_info needed to be updated to store dtypes in string
form.
=> Fix unit tests

katdal/__init__.py, katdal/applycal.py, katdal/datasources.py, katdal/flags.py, katdal/h5datav2.py, katdal/h5datav3.py, katdal/test/test_applycal.py, katdal/test/test_datasources.py, katdal/visdatav4.py, scripts/mvf_read_benchmark.py
The main speedups come from
- Building a separate dask graph from the corrections, so that the calculations can be recycled when loading vis, flags, weights jointly.
- Expanding CategoricalData (for B and K) into Python lists of arrays, which can be indexed much faster. This does have the downside of extracting all cal sensors when the file is opened rather than lazily, but for now that's only going to happen if the user explicitly requested applycal and so it is presumably going to happen sooner or later.
A major change is that calibration solutions are now computed and applied prior to stage1 selection. This may be slower in some cases where not all the data is accessed e.g. if the user is only selecting a subset of inputs, the calibration correction will still be done on all inputs and …
=> Second round of applycal optimisations

katdal/chunkstore.py, katdal/datasources.py, requirements.txt, setup.py
- Replace ShareDict with HighLevelGraph
- Replace da.atop with da.blockwise
- Unpin subprocess32 (not directly related)
This will first need dask>=1.1.0 to be put into katsdpdockerbase
defaults before it'll work.
=> Eliminate use of deprecated dask constructs

katdal/chunkstore_s3.py, katdal/datasources.py
If given an HTTP URL, interpret it as the location of an RDB dump file in an S3 object store. Use (or abuse) an S3ChunkStore object to access it, which handles the necessary authorization. Download the RDB object as a binary blob into memory and open it directly using the latest katsdptelstate. Then also use this S3ChunkStore as the actual chunk store in the absence of any overrides.
To enable the (ab)use of `S3ChunkStore`, upgrade the `_request` method to its public API by dropping the underscore.
This addresses JIRA ticket [SR-1443](https://skaafrica.atlassian.net/browse/SR-1443).
=> Load RDB files straight from archive

katdal/chunkstore_s3.py
This add an expiry_days parameter to the chunk store that is used
to create lifecycle policies for any new buckets the chunk store
makes.
Only allows integer days.
=> Allow an expiration time for new buckets to be set

katdal/visdatav4.py
As reported in MKAIV-1222, the initial SKARAB X-engines had their correlator output data lagging the corresponding SPEAD timestamps by one dump. This has been fixed in recent versions of SKARAB.
Add a workaround to correct the timestamps of older data sets. Mattieu provided empirical evidence of when various SKARAB versions were fixed.
This addresses JIRA ticket SR-1625.
=> Add workaround for one-CBF-dump offset

katdal/sensordata.py, katdal/test/test_chunkstore_s3.py, katdal/visdatav4.py
If a sensor is not found in the `SensorCache`, look it up in the katstore central database if a store address is provided. Retrieve the historical sensor values in the time range of the data set.
I've only enabled v4 support for now as I don't know if earlier sensor data is still available with the same REST API.
Usage:
```Python
f = katdal.open('1543151779_sdp_l0.full.rdb', sensor_store='portal.mkat.karoo.kat.ac.za')
f.sensor.get('cbf_1_target')
```
This addresses JIRA ticket SR-1710.
=> Retrieve raw sensor data from CAM katstore

katdal/datasources.py, katdal/sensordata.py, katdal/test/test_datasources.py, requirements.txt, scripts/mvf_rechunk.py, setup.py
The memory backend is now the default - no need to specify it.
Use the `TelescopeState.join` helper method instead of invoking the
namespace separator itself. Catch RdbParseError to improve error
reporting. Since `keys` and `prefixes` already return native strings
there is no need to override them in `TelstateToStr`. The RDBWriter
has been reworked. Remove fakeredis from package requirements.
=> Use features introduced in katsdptelstate v0.8

katdal/datasources.py
If the RDB file is opened via archive URL, use that URL and
corresponding S3 credentials or token to access the chunk store. This
has been decreed since it is the expected behaviour 99% of the time.
On-site chunk stores will be accessed via whitelists only, thereby not
requiring credentials or tokens, which removes the concern that
prevented this shortcut. Overrides are still possible via URL parameters
(and separate RDB retrieval) for custom use cases.
This reverts the change in commit 98cbc8a and addresses JIRA ticket
[SR-1443](https://skaafrica.atlassian.net/browse/SR-1443).
=> Restore chunk store inference from RDB URL

katdal/datasources.py
Just in case some process crashes before it can record it's stream type
in telstate.
=> Be more robust to missing stream_type

katdal/applycal.py, katdal/test/test_applycal.py, katdal/visdatav4.py
This updates "make L1" to be closer to what we need for L2:
- Remove hard-coded `cal` stream names. Make it part of the calibration product name instead.
- Remove `has_cal_product` which will be hard to support for virtual cal product sensors.
- Rename the virtual correction sensors to improve matches to funny stream names.
- Add virtual product sensors to standardise stream names to something like `l1` and `l2`.
- Minor doc updates and refactors.
So a "cal product" is now an amalgam of a cal stream (`l1`) and a product type (`G`), with a name like `l1.G`. The streams may be actual or virtual. The `add_applycal_sensors` function operates on a single cal stream at a time.
(EDIT: renamed `L1` to `l1`)
=> Make L2: preparations

katdal/applycal.py, katdal/test/test_applycal.py, katdal/visdatav4.py
- Introduce multi-channel gain products for the L2 stream. These perform linear interpolation along the time axis, while picking the closest cal channel for a given vis channel along the frequency axis.
- Self-cal solutions are obtained on a specific source and should only be interpolated to other data points of the same source. The gain correction routine therefore needs to be aware of the target associated with each dump in this case.
Both these behaviours are implemented for the new `GPHASE` and `GAMP_PHASE` product types.
There is some hackiness to get each stream's channel mapping to its point of application in `calc_correction`, but hopefully I'll clean this up as part of SR-1937.
=> Make L2: the Turn

doc/mvf_v4.rst, katdal/applycal.py, katdal/visdatav4.py
Hook up the L2 stream to applycal:
- Synthesise the indirect L2 products (GPHASE and GAMP_PHASE) by merging the raw sensor data of the underlying cal substreams. Do this by interleaving the timestamps of each sensor to form a combined raw `RecordSensorData` object.
- Register sensors for the standard "l1" and "l2" cal streams, if found. The "l1" stream is the first "sdp.cal" stream found in the list of archived streams (or "cal"), and the "l2" stream is derived from the first "sdp.continuum_image" stream in the list.
- Parse the string supplied to the `applycal` parameter of `katdal.open` and turn it into a list of fully qualified cal stream names. Both product types and cal streams may be specified independently. Also add a "default" grouping (which should eventually become the default …
=> Make L2: the Prestige

katdal/sensordata.py
The boolean values in katstore seem to be 'True' and 'False' instead of the old '1' and '0' of KATCP.
=> Fix decoder for boolean sensor values

katdal/dataset.py, katdal/ms_async.py, katdal/ms_extra.py, katdal/visdatav4.py, scripts/h5toms.py, scripts/mvftoms.py
This addresses a slew of recent tickets:
- [SR-1828](https://skaafrica.atlassian.net/browse/SR-1828): let `mvftoms` open RDB URLs, including access tokens. It turns out that this is already possible, thereby removing the need for #249... I only needed to fix the construction of a default output MS name. One thing to note is that the MS now goes into the working directory as always promised, instead of next to the RDB file.
- [SR-1811](https://skaafrica.atlassian.net/browse/SR-1811): Fix the optional REST_FREQUENCY column in optional SOURCE table. It is not optional for UVFITS export in CASA... Clean up the whole SOURCE sub-table. @sjperkins should have a good look at this.
- [SR-1948](https://skaafrica.atlassian.net/browse/SR-1948): Add `--applycal` option to pass through to …
=> Various fixes and improvements to MVFtoMS

katdal/dataset.py, katdal/h5datav1.py, katdal/h5datav2.py, katdal/h5datav3.py, katdal/test/test_dataset.py
This brings the `katdal.DataSet` (u, v, w) calculations in line with the rest of the ecosystem (`mvftoms`, `katsdpcal`, `katsdpimager`, ... thanks @bmerry!).
The speed-up is on the order of the number of baselines, measuring about 500x on a dataset with 60 antennas (1542913317). The accuracy was still to be verified in JIRA SR-1883, but since this has been in use since at least April 2018 in MSes produced by katdal and verified by Tom on PKS 1934-638, we can lay that part to rest.
One caveat is that this will break (u, v, w) on older MVF formats before v4 that do not yet define an 'array' antenna. We'll need to remedy that still.
This addresses JIRA ticket SR-1509 (and SR-1640).
=> Speed up (u, v, w) calculations

katdal/applycal.py, katdal/test/test_applycal.py, katdal/visdatav4.py
The gain sensors are unlikely to have a gain solution at dump 0, so the categorical sensor extraction shifts the first proper gain solution back to dump 0 to fill this void.
We want to avoid this for two reasons:
- Linear interpolation of gains over time will be compromised.
- The first gains will most likely land on a different target than intended, and this association can propagate it further in error.
One solution is to duplicate the first gain event at dump 0, but this requires `allow_repeats=True` and a manual duplication process. Instead, we set the initial value to `INVALID_GAIN`. When the gains are turned into corrections, discard this initial placeholder and let the usual extrapolation fill in the void instead. The placeholder is incommensurate with the usual sensor values that …
=>  Set initial value of gain sensors to INVALID_GAIN

doc/mvf_v4.rst
Spell out the shapes and dtypes of all calibration products.
Correct the description of `refant` which is soon the antenna name and not an antenna object description.
=> Update documentation for sdp.cal keys

katdal/chunkstore_s3.py
The fix in #260 forgot to use `.format`, so the ValueError ends up with
a tuple instead of an argument.
=> Fix formatting of ValueError

NEWS.rst, setup.py
Also bump requirement on katpoint v0.9 which will be released simultaneously.
This addresses JIRA ticket [SR-1734](https://skaafrica.atlassian.net/browse/SR-1734).
=> Prepare for v0.14

scripts/mvftoms.py
The previous hard-coded list (in the help) was missing the postproc
flag. I also put spaces after the commas so that it would wrap sensibly.
See SPR1-185.
=> Make mvftoms get flag names from katdal.flags

katdal/dataset.py
katpoint.Catalogue.__contains__ treats all strings as names rather than
descriptions, which broke selection-by-description because it was
short-circuited by the check for whether the target was present.
Now uses exception handling to detect targets not in the catalogue.
Closes SR-1819.
=> Fix selection by target description

katdal/chunkstore_s3.py, katdal/datasources.py, katdal/test/test_chunkstore_s3.py
I'm splitting the chunk store rework into at least four PRs to lighten your load...
1. Initial refactor to get rid of icky layers of code [THIS ONE]
2. Token checking and authorisation error reporting (done, waiting in the wings)
3. Timeout and retries rework (current activity)
4. Collect request response statistics for debugging (future work)
Some of these bits (like da08290) are reworked in the future PRs, but not by a lot.
@sratcliffe, you'll like this one because it addresses your concerns in #235 😄
=> SPR1-181: initial refactor

katdal/chunkstore.py, katdal/chunkstore_s3.py, katdal/datasources.py, katdal/test/test_chunkstore_s3.py
This is a rather large PR in three parts:
- The first two commits introduce the basic improvements and tests for it
- The next bunch (up to 24b57b6) refactors and removes quite a bit of code
- The last commits introduce a unified approach to 50x errors and reset connections via explicit retries
=> SPR1-181: Improve timeouts and retries

katdal/chunkstore_s3.py, katdal/test/test_chunkstore.py
PR #274 broke `mark_complete` when run on a whole bucket, because it
calls `create_array` which now crashes if the "array_name" doesn't have
a separator.
This keeps the behaviour for `create_array`, but adds a backdoor
`_create_bucket` so that `mark_complete` can once again put a completion
marker at the bucket level.
=> Make mark_complete work on whole bucket again

katdal/test/test_chunkstore_s3.py
Since we are connecting to a local HTTP proxy server running on a
second Python thread in the same process, things can get a bit jerky.
Increase the connect timeout substantially to 5 seconds. Also redo the
unresponsive server test and give it its own (short) timeout without
retries to speed it up (no need to wait for 10 seconds).
This addresses JIRA ticket SPR1-364.
=> Increase S3 connection timeouts in unit tests

katdal/chunkstore_s3.py
The current error message is the default one provided by PyJWT which
reads "Signature has expired" - but what is a "signature"? To help the
end user, call it a token instead and include the expiry date/time for
handy reference. Also mention that the correct course of action is to
obtain a new one (thanks Ruby!).
This addresses JIRA ticket SR-1971.
=> Improve error message for expired tokens

katdal/applycal.py, katdal/test/test_applycal.py, katdal/visdatav4.py
This applies a flux scale to those gains of the "G" calibration product that are associated with gain calibrator targets with a valid flux density in the `gaincal_fluxes` dict. More specifically, the gains are multiplied by the square root of the flux, which turns the default flux model value of 1.0 into the appropriate flux for the gain calibrator. The fluxes are obtained from the `measured_flux` telstate key produced by the cal pipeline but it can also be overridden via `katdal.open` or disabled by specifying an empty dict.
This is equivalent to the final step of the AIPS GETJY and CASA fluxscale tasks.
This addresses JIRA tickets SPR1-67 and SPAZA-27.
=>  Add flux calibration to applycal

katdal/applycal.py, katdal/test/test_applycal.py, katdal/visdatav4.py
- Look for `measured_flux` in the right place by adding relative telstate views to access `cb_cal` namespace
- Divide gains by flux instead of multiplying it
There is also a slight rework of `_register_standard_cal_streams` to use the new relative views.
=> Fix flux calibration

scripts/mvf_rechunk.py
0b1da5c filtered out non-visibility streams from mvf_rechunk, but
sdp.flags streams were thrown out with the bathwater.
=> Allow mvf_rechunk on sdp.flags streams again

scripts/mvf_read_benchmark.py
This is makes it much easier to see variability, and also to get an idea
of read speed without going through the whole file.
=> Log bandwidth of each load in mvf_read_benchmark

katdal/chunkstore.py, katdal/datasources.py, katdal/test/test_chunkstore.py
Instead, just try to load things, and if any of them fail, apply flags.
This has a few advantages:
1. chunkstore_s3 is non-deterministic, because it will treat a 403 or
50x error as a missing chunk even if the bucket listing included the
chunk. This meant that even when loading vis, flags, weights jointly,
the vis/weights could be missing and the flags wouldn't reflect this (or
if the flags got a 50x, it would return zero flags). With this change,
joint loading should always return consistent results.
2. Getting the list of all chunks could add a lot of time to
`katdal.open`, which now disappears.
A synthetic benchmark (with no applycal) shows that loading drops from
about 3.3GB/s to about 3GB/s, but that's still faster than the 25Gb/s
network can deliver the data.
This is part 1, which …
=> Avoid using has_array in ChunkStoreVisFlagsWeights

katdal/applycal.py
`set(targets)` showed up as a hot-spot. Moving it to the outer loop cuts
over a minute off the startup on a big data set.
=> Optimise calc_gain_correction by reordering loops

katdal/applycal.py, katdal/sensordata.py, katdal/test/test_applycal.py, katdal/visdatav4.py
Instead of Calibration/Products/cal/B<n> which have to be stitched
together across frequencies to form the bandpass solution, there is now
a virtual Calibration/Products/cal/B which handles the stitching
internally. This allows it to be cached once extracted.
=> Cache combined bandpass

katdal/h5datav3.py
It was being turned into a string via %d, but in some old files (e.g.
1462454843.h5) it ended up encoded as a string already, causing this to
crash.
=> Cope with rx_serial being a string

katdal/h5datav2.py, katdal/h5datav3.py
For dummy_dataset (the real file already does it). This avoids a
deprecation warning from h5py that the default mode will change to 'r'.
=> Explicitly pass file mode to h5py.File

katdal/sensordata.py
Katstore samples sensors at least once every 10 minutes (not seconds!), so we have to go that far back in our search to ensure that we get values for discrete sensors that change very infrequently (like the band setting). If not, short 5-minute observations like delaycals can miss a sensor value completely.
=> Increase katstore search window by 600 seconds

katdal/visdatav4.py
It had a hard-coded assumption that the instrument is called i0, which
is no longer true.
Closes SPR-435.
=> Fix calculation of cbf_dump_period

katdal/concatdata.py, katdal/sensordata.py, katdal/test/test_concatdata.py, katdal/test/test_sensordata.py
This provides more predictable/controllable behaviour compared to
inheriting directly from dict. I also made some fixes to
ConcatenatedSensorCache regarding iteration and length (previously it
implemented iterkeys, which didn't work at all in Python 3 and also made
the assumption that the underlying caches had exactly the same keys).
Querying a sensor cache can cause new keys to appear in the underlying
dict (as virtuals are expanded), so it was necessary to make some
choices). I decided that __contains__ will only consider instantiated
keys, not virtuals, making it consistent with `keys()` and `len` (and
the previous implementation of SensorCache), but inconsistent with
`__getitem__`.
One user-visible change in SensorCache is that `items()` and `.values()`
will now return extracted data, …
=> Use MutableMapping for SensorCache

Jenkinsfile, doc-requirements.txt, requirements.txt, test-requirements.txt
Now that katsdptelstate is Python 3 only, the Python 2 unit tests are
failing.
=> Run tests against Python 3 only

katdal/sensordata.py, katdal/test/test_sensordata.py
After sorting the sensor timestamps, the values are updated accordingly but not the statuses, which is a bug. Normally this is not an issue because timestamps tend to be chronological anyway. The somewhat insidious interaction between value and sample/update timestamps may however occasionally cause a later event to be sampled before an earlier event. An example is the `cbf_1_wide_input_labelling` sensor during CBID 1588667937 which triggered this fix.
Add a test to check this corner case and also exercise the various code paths in the filter function.
=> Fix filtering of sensor events with invalid status

katdal/test/s3_utils.py, katdal/test/test_chunkstore_s3.py
This will make it practical for other packages to reuse the code.
It is deliberately designed not to use the SkipTest exception, which is
specific to nosetests, so that it can easily be integrated into other
test frameworks (pytest).
The version test has been removed and left to documentation: newer
versions of minio have a different way of querying the version, and it
didn't seem worth trying to support both flavours.
=> Split out separate utility classes for Minio

NEWS.rst
I forgot to add the 0.16 release notes to master (it was done in the python2 branch).
Cherry-pick these in place instead of merging in order to keep the commit graph nice. It was already a belated release, so I prefer that the python2 branch remain unmerged to help find the spot on master that is the "actual" v0.16.
=> Release v0.16 redux

katdal/datasources.py
Kwargs now flow to `TelstateDataSource.__init__` too, but if the CBID and/or stream name are specified in kwargs, they clash with the explicit versions passed to the constructor. The solution is to clear them out of kwargs after `view_l0_capture_stream` picked them up.
I've postponed the unit test improvements to a later PR since that part has grown quite a bit.
=> Fix kwargs bug introduced by #316

katdal/chunkstore.py, katdal/chunkstore_s3.py, katdal/test/test_chunkstore.py, katdal/test/test_chunkstore_s3.py, katdal/test/test_datasources.py
I managed to push the test coverage of this critical module from 59% to 91%, hopefully avoiding the kinds of errors introduced by #316 in future.
In the process I also improved general S3 error reporting and extended `S3ChunkStore` to accept store URLs with paths (mostly a bucket creation issue).
=> Datasource unit tests

NEWS.rst, setup.py
This reverts PyJWT to 1.x in order to support Python 3.5 one last time.
=> Prepare for v0.17

katdal/test/test_datasources.py
The previous value was far enough in the past to trigger workarounds for
CBF bugs in VisibilityDataV4. Change it to a more modern era to
facilitate use with VisibilityDataV4.
=> Change sync time used in fake data set

doc/tuning.rst, katdal/__init__.py, katdal/chunkstore.py, katdal/datasources.py, katdal/test/test_chunkstore.py, katdal/test/test_chunkstore_npy.py, katdal/test/test_chunkstore_s3.py, katdal/test/test_datasources.py, katdal/test/test_vis_flags_weights.py, katdal/vis_flags_weights.py, katdal/visdatav4.py
This avoids the cost of building up a massive graph only to select most of it away, and also saves memory since that large graph won't be kept around.
I'm marking this as draft for now because I'm not sure how best to handle pre-MVFv4 (see below). Nevertheless, please review to see if you're happy with the overall approach.
The problem is that an application that wants to use this feature won't necessarily know which version file it is opening, and hence the argument might or might not be ignored. It can check the file version after the fact, but then it would still need to hard-code knowledge of which versions support the feature, and that may change over time.
There are a few possibilities:
1. Just support it in all versions. I haven't looked at LazyIndexer to see how practical this is. …
=> Allow subset to be selected at katdal.open time

setup.py
llvmlite 0.32.0 was the last to support python 2, but the default dependency check looked for >=0.31.0dev0
=> fix llvmlite version for python 2

katdal/sensordata.py, katdal/test/test_sensordata.py
The latest major version of h5py (3.0, released Oct 2020) totally
revamps string handling. All string-valued attributes in MVF3 now
return `str` in Python 3 (while h5py 2.x returns `bytes`).
Extend `telstate_decode` to handle both versions and add some tests.
=> SPR1-910 Support h5py 3.0 API in MVF3

NEWS.rst, setup.py
Restore the version constraint on katpoint now that ska-sa/katsdpdockerbase#67 is merged. Include #331 in changelog.
Update release date.
=> SPR1-894 Prepare for v0.18 (take 2)

katdal/ms_extra.py, scripts/mvftoms.py
It is time...
@mauch, I used the script you modified for @nirujmohanr as basis, and also threw in scans for good measure.
=> KAT-1196: Support planets and other non-radec targets in mvftoms

katdal/concatdata.py, katdal/visdatav4.py
Expose the raw flags of MVFv4 datasets, which are the uint8s stored in the chunk store (L0 or L1), augmented by the `data_lost` bit that also covers the corresponding vis and weights chunks, and the `postproc` bit produced by the optional applycal step. It is therefore the final flag bits before they are combined into bools, which tells you why data points are flagged.
The `raw_flags` indexer will honour stage 1 and stage 2 selections done on the time, frequency and corrprod axes, but ignores flag selections. It always returns all available flag bits.
Also refactor some of the cruft in `_set_keep` while we are at it.
=> SPR1-897: Expose the raw flags of MVFv4 datasets

katdal/lazy_indexer.py, katdal/test/test_lazy_indexer.py, katdal/visdatav4.py
The main use case is to slap some more transforms onto an existing indexer (think `flags` piggy-backing on `raw_flags`) but it also allows N-stage indexing. The first indexer's `dataset` Dask array becomes the original dataset for the second indexer (lazily), and an additional selection and transform set will then be applied to it to form the `dataset` of the second indexer.
It's only used for the flags indexers for now.
=> SPR1-897: Allow nested DaskLazyIndexers

scripts/mvftoms.py
Multiprocessing changed its default process start method on macOS to "spawn" in Python 3.8. This requires the parameters to `Process.__init__` to be picklable. One of them is an instance of the `CPInfo` namedtuple. This class is defined locally in the `corrprod_index` function, where pickle cannot find it.
Fix the issue by moving the definition of `CPInfo` to the module/script level.
=> SPR1-1210: Fix mvftoms on macOS and Python 3.8+

katdal/visdatav4.py
There is now the following set of virtual sensors that expose the underlying CBF sensors (`wide_antenna_channelised_voltage_{inp}_delay/eq`) in a more katdal-friendly way:
```
Correlator/Inputs/{inp}/applied_delay [seconds]
Correlator/Inputs/{inp}/applied_phase [radians]
Correlator/Inputs/{inp}/applied_gain [complex64, shape (n_chans,)]
```
The idea is to use them to undo delay tracking and/or F-engine gains.
@spassmoor I recall you did similar experiments at some stage, so I'm including you in the review mix.
PS the `applied_phase` sensor is there for completeness but I'm still figuring out the best way to use it in delay tracking inversion.
=> SPR1-1138: Improve the exposure of CBF sensors

katdal/dataset.py, katdal/test/test_dataset.py
This change allows the deselection of a set of antenna by prefacing the antenna with ~
=> SPR1-1143: Allow deselection of antennas in katdal using '~m0XX'

katdal/chunkstore_s3.py, katdal/test/test_chunkstore_s3.py
Whenever a chunk is not found, go and check the associated bucket. If the bucket is missing or empty, raise `StoreUnavailable` instead since this is a fatal error. In the past katdal would happily return a bucketload of zeros with no complaints.
The bucket exists but is empty if the dataset has been archived to tape. A completely missing bucket is unlikely, but check for it anyway.
~~We perform the check with every missing chunk because that is simpler than tracking which buckets we verified. The overhead should be low, since we typically either have all chunks missing (the aim of this fix) or only a handful of chunks missing. Besides that, 404s are quite quick compared to the downloading of actual chunks.~~
We cache all verified buckets on the store, assuming that a bucket won't empty …
=> SPR1-766: Verify that S3 bucket is not empty

katdal/chunkstore.py, katdal/test/test_chunkstore.py, katdal/test/test_chunkstore_dict.py, setup.py
The latest dask has renamed `da.core.getem` to `da.core.graph_from_arraylike` with a different interface (see dask/dask#7417). Revisit the `ChunkStore.{get|put}_dask_array` machinery to replace `getem`.
~~For the "get" case we stick with `getem` in older dasks, and switch to `graph_from_arraylike` in newer ones.~~
For the "get" case we revert to `da.from_array` with a custom arraylike object and getter function.
For the "put" case we switch to `da.map_blocks` all around (but we would ideally like to use `blockwise` in the future).
More rationale follows 😄
=> SPR1-1944: dask 2022.01.1 breaks katdal due to missing da.core.getem

scripts/mvf_copy.py, scripts/mvf_rechunk.py, setup.py
This makes a local copy of an MVF4 dataset (local or remote). In the
process it also allows stripping out correlation products. It currently
only supports extracting the autocorrelations via the `--corrprods=auto`
script option. The filtered RDB file and chunks are stored in a new
subdirectory (by default "./archive").
The script has much in common with `mvf_rechunk.py` and might eventually
merge with it.
=> SPR1-1737: New mvf_copy.py script

katdal/chunkstore_s3.py, katdal/test/test_chunkstore_s3.py
The original MeerKAT Ceph RADOS Gateway returned a 403 (Forbidden) for missing objects due to a bug in the interaction with the bucket policy. We therefore treated 403 as 404 and raised `ChunkNotFound`. See #273, 09e100d and 5a7790c for more details.
The current gateway has fixed this, and missing objects now return 404 as expected. Treat 403 the same as 401 and raise `AuthorisationFailed` instead.
I could not find any external user code that caught the old exception, so the update seems safe to roll out.
=> SPR1-1401: Fix the handling of 403 errors

katdal/ms_extra.py
This column is initialised full of zeroes and just takes up space (4 bytes per main table entry, i.e. time-frequency-baseline cell, so about 6-12% overhead). It can be recreated in CASA at a later stage.
The column is a leftover of good old `blank.ms`, which included it along with `MODEL_DATA` and `CORRECTED_DATA`. The latter two columns were made optional in the sneaky 41af4b8 as part of #75 in version 0.9, but this one was missed.
Testing an MS produced by the new code would be much appreciated.
=> SPR1-2367: Remove IMAGING_WEIGHT column from MS

katdal/test/s3_utils.py, katdal/test/test_chunkstore.py, katdal/test/test_chunkstore_s3.py, setup.py, test-requirements.txt
Since around May 2020 (v0.17 or so) the failure rate of unit tests on Jenkins has gone up a lot. Interestingly, these issues do not occur on my MacBook Pro or on an equivalent Docker container used outside Jenkins (with identical MinIO version etc).
The failures are mostly attributed to:
- broken pipes in token proxy server
- read timeouts on MinIO (especially large dask array activity)
- 503 errors on MinIO startup (typically manifests during `test_chunk_bool_1dim_and_too_small` test)
- duration check failures (not addressed yet)
While we are at it, make the tests pass with the latest PyJWT.
=> SPR1-2674: Fix unit tests on Jenkins

katdal/averager.py, katdal/categorical.py, katdal/concatdata.py, katdal/dataset.py, katdal/h5datav1.py, katdal/h5datav2.py, katdal/h5datav3.py, katdal/lazy_indexer.py, katdal/ms_extra.py, katdal/sensordata.py, katdal/test/conftest.py, katdal/test/test_applycal.py, katdal/test/test_chunkstore.py, katdal/test/test_chunkstore_dict.py, katdal/test/test_chunkstore_npy.py, katdal/test/test_chunkstore_s3.py, katdal/test/test_concatdata.py, katdal/test/test_dataset.py, katdal/test/test_datasources.py, katdal/test/test_lazy_indexer.py, katdal/test/test_sensordata.py, katdal/test/test_spectral_window.py, katdal/test/test_vis_flags_weights.py, katdal/vis_flags_weights.py, katdal/visdatav4.py, pytest.ini, setup.py, test-requirements.txt
Nose hasn’t been updated in 7 years and finally does not run on Python 3.10 anymore. This makes it irritating to test katdal, which now needs a Python 3.9 environment just for testing.
Convert all the tests to pytest. Try the nose2pytest script to help with this.
In the process, make the duration checks optional on Jenkins (where it frequently fails with large discrepancies).
Also resolve a bunch (269 928!) of NumPy deprecation warnings.
=> SPR1-2674: Move unit tests from nose to pytest

katdal/chunkstore_s3.py, katdal/datasources.py, katdal/test/test_chunkstore_s3.py
This improves the robustness of katdal's archive access.
While glitches where typically picked up while reading the response header, the response body had no such checks, as is the wont of the Requests library (only discovered that now 😅). Since the bulk of the data resides in the body, this meant that chunk transfers were rarely retried.
Fix this by integrating retries into the response reading too. Maintain a single `Retry` object per session, which is passed to the request, retrieved from the response and updated in case the response content has issues. Completely overhaul `S3ChunkStore.request`. Replace `TruncatedRead` with the more standard `IncompleteRead` exception. Retries can now be overridden per request.
This gets rid of the clunky fake 555 status code that treats truncated …
=> SPR1-813: Handle truncated reads, socket timeouts and reset connections (aka glitches) in S3ChunkStore

katdal/dataset.py, katdal/test/test_dataset.py
A `katpoint.Catalogue` can have multiple different targets with the same name, usually differing in tags only. The DataSet selection mechanism [`d.select(targets="name")`] still used a dict-style lookup for target names though, which is constrained to return a single target: the last target with the given name.
This would normally not be a big issue as there are other ways to select targets. It became a problem after #269 (released in katdal 0.18 in April 2021) which added field selection to `mvftoms.py`. This now always selects targets by name, even if the user wants all the targets and the selection is therefore unnecessary. This caused folks to lose e.g. a flux or bpcal calibrator in the MS conversion if they used the same target as a gain calibrator later on in the observation.
Fix …
=> SPR1-2912: Select multiple targets with the same name

katdal/averager.py, katdal/chunkstore_s3.py, katdal/test/test_chunkstore_s3.py
Before 19 December 2018 the MeerKAT Ceph archive had underscores in its S3 bucket names, even though it was in violation of the S3 spec. Since October 2023 the archive runs a stricter version of Ceph and those older buckets were renamed to use dashes / hyphens instead. The metadata in the corresponding RDB files still refer to bucket names with underscores though.
Use the `S3ChunkStore.make_url` method as a centralised tool to build URLs from paths, fixing the underscores in the bucket names in the process. All store URLs should emanate from this method.
Some alternatives I considered:
- Fix the vis prefix in the RDB file or as it comes out in telstate (downside: the prefix applies to NPY stores as well and there are also flag bucket prefixes to consider - maybe still an option...)
- Fix …
=> SPR1-2990: Change underscores in S3 bucket names to dashes
