katdal/h5datav3.py
If `sdp_l0_bls_ordering` is present in the TelescopeState, it is used instead of `bls_ordering` in the CBF component of the telescope model.
This depends on ska-sa/katsdpdata#55.
=> Prefer sdp_l0_bls_ordering to cbf_bls_ordering

katdal/ms_extra.py, scripts/h5toms.py
Creates B, K and G caltables in h5toms.py if the solutions are present in the h5 file
=> Output calibration solution tables in MS format

katdal/ms_extra.py
I have add the source id's to the FIELD table because the -1's look weird .
=> Add source ids to FIELD table

katdal/ms_extra.py
Fix the types of the source id's in the field table and other miscellaneous variables
=> Fix source ID types

katdal/h5datav3.py
The standard UHF receivers have a digitiser sampling at 1088 MHz with an unflipped bandwidth of 544 MHz in the second Nyquist zone (544 - 1088 Mhz), resulting in a centre frequency of 816 MHz.
Delegate the old "fake" UHF receiver to the corner cases (only active if the bandwidth is 856 MHz, i.e. it uses an L-band digitiser). Move the calculation of bandwidth and channels earlier to facilitate this.
=> Support standard UHF receivers

scripts/h5toceph.py
This script gets the ball rolling with using Ceph to store data sets.
I'm merging this now so that I can access the script while working on master to refactor DataSet.
=> Initial Ceph investigation: h5toceph

katdal/h5datav3.py
The SDP ingest emits a partial dump at the end of a capture which consists of the leftover CBF mini-dumps. The last timestamp might therefore not be exactly one dump period after the second-to-last one, unnecessarily triggering this warning about excepted dumps being out.
The solution is to use the second-to-last timestamp in the check.
PS In the multi-ingest future the last dump will be aligned with the rest again, so ignore this fix for v4.
=> Relax expected dump check

katdal/dataset.py
This PR makes the following functionality available:
```python
K = katdal.open(...)
K.select(pol="HH,VV")
```
=> Allow selection of multiple polarisations

katdal/h5datav3.py
Attributes are now looked up all the places they might exist. Using
current typical names, these would be:
- sdp_l0_int_time
- l0_time time in SDP TelescopeModel
- i0_baseline_correlation_products_int_time
- cbf_i0_baseline_correlation_products_int_time
- i0_antenna_channelised_voltage_int_time
- cbf_i0_antenna_channelised_voltage_int_time
- i0_int_time
- cbf_i0_int_time
- int_time in CBF TelescopeModel
Not all of these make sense, but it should make sure we find anything
there is to find, and hopefully the precedence order is correct.
=> Look for attributes in more places in v3

katdal/chunkstore_rados.py, katdal/dataset.py, katdal/datasources.py
This is quite a hodge-podge of stuff to get the first v4 reader going:
- Open RDB files with `TelstateDataSource`
- Use the chunking metadata in telstate to build a `VisFlagsWeights` that speak to the chunk store (only RADOS for now)
- Make the dask arrays work like the old LazyIndexers
The next step would be to gussy up the V4 formatter based on this data source (and add S3 support).
=> SR919: Add ChunkStore-based VisFlagsWeights to TelstateDataSource

katdal/datasources.py
A quick one...
If the `s3_endpoint_url` key is found in telstate, prefer that to the RADOS option. The chunk_name is gone for now (since it should be simply the capture stream name), but it might make a comeback once the data source builds from a viewed-up telstate only.
=> Add support for an S3 chunk store to TelstateDataSource

katdal/h5datav3.py
The latest version of HDF5v3 (presumably live on 2018-02-21) contains some elements of v4. The obs sensors live in a `capture_block_id` namespace in telstate, and `obs_params` is now a dict-valued attribute instead of a sensor of 'key repr(value)' strings. This is indicated by the presence of `capture_block_id` in the top-level file attrs.
=> Support v3.9 files

katdal/datasources.py
Since katsdpingest PR [#229](https://github.com/ska-sa/katsdpingest/pull/229) it is now possible to synthesise the correlator timestamps based on the number of dumps and the following telstate keys:
- `<stream>_sync_time`
- `<stream>_int_time`
- `<cbid>_<stream>_first_timestamp`
This has a number of advantages. The data set can be interpreted without resorting to the chunk store, simplifying metadata extraction. The timestamps chunk was a small silly thing to begin with. Synthesis also enables more accurate timestamps as more bits are available for each timestamp.
=> Synthesise correlator timestamps from telstate

katdal/chunkstore_s3.py
Instead of storing the chunk array buffer as a binary string in S3, rather store the string representation of the corresponding NPY file, which is the buffer along with a (small) additional header.
This has several advantages:
- The vis trawler and other similar tools can upload NPY files straight into S3 (or download them the same way). This is a very efficient way to convert an `NpyFileChunkStore` to an `S3ChunkStore`.
- The header contains the shape and, more important, the dtype of the chunk. This allows us to remove the `dtype` parameter being passed around all over `ChunkStore` and brings it closer to the dask.array idea of a store (as used in the `dask.array.store` function), or even [zarr](https://github.com/zarr-developers/zarr).
- Benchmarks indicate that the new format somehow …
=> Store NPY files directly in S3

scripts/objtoms.py, setup.py
Quick and nasty so we have an objtoms.py for the QTR and can point to a master version of katdal that has it... Easiest is just to diff objtoms.py and h5toms.py
=> Added objtoms.py

katdal/ms_extra.py, scripts/mvftoms.py
There are a number of changes - refer to individual commits for details. Note that UVW coordinates will change very slightly.
This does introduce a hard dependency on dask, which I'm not sure how you want to handle, and which should be addressed before merge. I'm not sure if you're already planning to make it a hard dependency as part of the v4 release cleanup.
=> Optimisations to mvftoms.py

katdal/ms_extra.py, scripts/mvftoms.py, setup.py
The big difference in user experience is that it uses numba.
The FLAG_CATEGORY column is also changed to contain the flags instead of zeros.
If reviewing a commit at a time, you may want to look at the first two commits as a unit, since the second rewrites a lot of the first.
=> Further mvftoms.py optimisations

katdal/lazy_indexer.py, katdal/visdatav4.py, scripts/mvftoms.py
This is a hodge-podge of separate optimisations. See the individual commits for details.
=> Round 3 of mvftoms optimisations

katdal/dataset.py, katdal/h5datav2.py, katdal/h5datav3.py, katdal/visdatav4.py, scripts/mvftoms.py
This addresses the minor complaints of JIRA tickets COMM-315 and COMM-316.
And then I got seduced into flake8-ing the beast (again, now two years later).
=> Minor mvftoms fixes

katdal/chunkstore_s3.py, katdal/test/test_chunkstore_s3.py
This is to pair with ska-sa/katsdpauth#5
=> Add support for token-based authentication

katdal/datasources.py, katdal/test/test_datasources.py
If telstate has the 'sdp_archived_streams' key and it lists additional
streams (only in the full RDB), take each stream's 'chunk_info' dict
and let it override the corresponding entries in the default L0 one.
This specifically allows the additional 'sdp_l1_flags' stream to
override the 'flags' array in 'sdp_l0'.
In the process, refactor the chunk_info entries to contain the relevant
prefix aka base_name aka chunk_name, which is the prefix to be added
to the basic array name to find the array in the chunk store. This
makes it trivial to mix and match arrays between arbitrary S3 buckets
and NPY subdirectories. It's a pity this was not the original design
as the 'chunk_name' telstate key could then be chucked...
This addresses JIRA ticket …
=> Incorporate L1 flags into L0 product

katdal/averager.py
Instead of working along one axis at a time, the time and frequency
averaging are accumulated in a single pass. The loop ordering is also
set up to optimise cache usage.
=> Speed up the averaging using numba

requirements.txt
Needed due to ska-sa/katsdpdockerbase#18.
=> Add new requests requirements

katdal/chunkstore_s3.py
=> Increase default timeout for S3ChunkStore

katdal/datasources.py
If a vis or flags stream has an `inherit` member in telstate, the
telstate view will be constructed to have that stream in the telstate
view chain. This supports SR-1348 / ska-sa/katsdpdata#126.
view_capture_stream now just does the work of constructing a telstate
from capture_block_id and stream_name, and the "smart" version is now
view_l0_capture_stream (name chosen since it asserts that the type is
sdp.l0).
=> Handle stream inheritance

katdal/applycal.py, katdal/test/test_applycal.py
The gain solutions are linearly interpolated in time across any invalid solutions with NaNs (unless all gains for a particular input are bad).
This addresses JIRA tickets SR-1218, SR-1219 and SR-1251.
=> Make L1: gain

requirements.txt
- Add msgpack (see SR-1366)
- Unpin botocore and jmespath (now pinned in base)
=> Updates to requirements.txt

katdal/visdatav4.py
The katdal "reference antenna" (no relation to the calibration ref ant) is used for three things during construction of a `DataSet`:
- It provides the activity sensor that partitions data set into scans
- It provides the target sensor that identifies all the targets
- It serves as the default antenna for the DataSet catalogue
The default reference antenna (obtained by setting `ref_ant` parameter to `''`) is currently the first antenna in the list. This is very problematic if the first antenna misbehaved (see e.g. tickets SR-1383
and COMM-342). In the absence of an explicit reference antenna (the default case), now do the following:
- Use the `obs_activity` sensor to partition the data set (this is what the array intends to do, not what individual antennas actually do)
- Use the …
=> Remove default reference antenna from v4 data sets

katdal/__init__.py, katdal/averager.py, katdal/categorical.py, katdal/chunkstore.py, katdal/chunkstore_s3.py, katdal/concatdata.py, katdal/dataset.py, katdal/datasources.py, katdal/h5datav1.py, katdal/h5datav2.py, katdal/h5datav3.py, katdal/lazy_indexer.py, katdal/ms_async.py, katdal/ms_extra.py, katdal/sensordata.py, katdal/spectral_window.py, katdal/test/test_chunkstore.py, katdal/test/test_chunkstore_s3.py, katdal/test/test_datasources.py, katdal/test/test_lazy_indexer.py, katdal/test/test_sensordata.py, katdal/test/test_spectral_window.py, katdal/visdatav4.py, scripts/mvf_read_benchmark.py, scripts/mvftoms.py, setup.cfg
Replace `dask.set_options` with `dask.config.set`, as suggested by the dask TypeError.
Oh, and flake8 FTW.
=> Fix deprecated dask in script

katdal/applycal.py, katdal/dataset.py, katdal/test/test_applycal.py
Two issues:
- Using applycal without first `select()`ing something crashes
- The delay correction is the wrong way around (sign error)
This addresses JIRA ticket [SR-1575](https://skaafrica.atlassian.net/browse/SR-1575).
=> Fix some applycal issues

katdal/datasources.py, katdal/test/test_datasources.py
Fixes SR-1584. This does make some breaking changes to the low-level
public API: view_l0_capture_stream returns the CBID and stream name, and
TelstateDataSource.__init__ takes them. I searched Github and didn't
find any code that calls these functions, so we are probably okay.
Also adds a very basic unit test that ensures the upgrade occurs even
without the telstate keys for capture_block_id/stream_name.
=> Pass capture_block_id and stream_name to _upgrade_flags

katdal/datasources.py, katdal/test/test_datasources.py
The previous strategy was to take the number of dumps in the original
info as golden, and extend or truncate the improved info to fit. That
won't work so well with multi-dump chunks.
Instead, set the number of dumps to be the largest amongst all arrays
(after upgrades), and extend any array that is shorter to ensure a
match. That means that some files may now appear to have extra dumps for
which all the original data is missing, which will then be flagged.
Another side effect is that when not specifying a chunk-store OR
timestamps, the upgrade process is still done just to determine how many
dumps there are.
This should theoretically work with multi-dump chunks, but that has yet
to be tested.
=> Change padding strategy for upgrade_chunk_info

katdal/test/test_datasources.py
This is hopefully the final piece of SR-1330.
=> Add TelstateDataSource tests with multi-dump chunks

katdal/datasources.py
Depends on ska-sa/katsdptelstate#71.
=> Use new telstate MemoryBackend when reading from file

katdal/applycal.py, scripts/mvf_read_benchmark.py
Refer to the individual commits for explanation.
=> Initial work on speeding up applycal

katdal/datasources.py
- Reduce the dtypes of the index arrays (makes a few % improvement).
- Use np.reciprocal to compute 1/x, instead of the previous method which
created a temporary array.
- Multiply the weight scale factor with the weight as part of the
operation, instead of as a separate step (big improvement).
Together these give about a 25% improvement in throughput on my laptop
(when reading from cache). It will probably be less in real-world usage
as it will be more I/O-bound.
=> Optimisations to weight power scaling

katdal/datasources.py, katdal/sensordata.py, scripts/mvf_rechunk.py
It currently only supports output to local filesystem (and read from S3
isn't tested either), and should be considered an engineering
development tool rather than a user tool (which is why it doesn't get
installed by default).
=> Add rechunker script

katdal/chunkstore_s3.py, katdal/test/test_chunkstore_s3.py
A variety of nasty tricks to make requests go faster.
=> Optimise reads from S3

katdal/ms_extra.py
This fixes a 90 degree polarization rotation in exported measurement
sets.
Closes SR-1647.
=> Fix RECEPTOR_ANGLE in mvftoms

katdal/applycal.py, katdal/datasources.py, katdal/h5datav2.py, scripts/mvftoms.py
- A leftover commit from applycal (docs and line lengths and reordering code in module)
- Crash gracefully when trying to open invalid URLs
- Remove deprecated h5py feature (shout-out to KAT-7!)
=> Minor fixes

NEWS.rst, README.rst
Also update the changelog for v0.13 release.
=> Update docs to mention RDB and archive access

katdal/applycal.py, setup.py
As of dask 1.2.1, map_blocks can be used to achieve the same thing.
=> Remove from_block_function

doc/conf.py, doc/data_set_format.rst, doc/mvf_v4.rst, doc/signs.rst, doc/user.rst
Also contains some general documentation on sign conventions.
@KimMcAlpine could you write something for the KCROSS_DIODE and BCROSS_DIODE sensors?
@ludwigschwardt maybe you could add some documentation about the selfcal solutions?
=> More documentation of MVF v4

katdal/dataset.py, katdal/sensordata.py, katdal/test/test_dataset.py, katdal/test/test_sensordata.py
This is in preparation of the (u,v,w) speed-up PR.
Highlights:
- Unit tests! The `MinimalDataSet` class is quite nifty.
- Improved code-level documentation and refactoring.
=> Clean up virtual sensors

katdal/datasources.py
I think dask was inspecting the dict of lost chunks for every block.
When there were many lost chunks, this caused it to use huge amounts of
time and memory to load the file.
=> Improve open performance when many chunks lost

katdal/chunkstore_s3.py, katdal/test/test_chunkstore_s3.py
=> Detect short reads from S3 archive

katdal/ms_async.py
It uses new features in katpoint (including ska-sa/katpoint#51).
See SPR1-137.
=> Simplify UVW coordinate calculation in mvftoms

katdal/sensordata.py
Since CAM v24 release the katstore API has changed to katstore64. This does away with the need to query the sensor KATCP type, since the HTTP request now returns a JSON string with the appropriate value type. Having one HTTP request instead of two speeds things up, on top of the improved performance of katstore64 itself.
This addresses JIRA ticket [SR-1962](https://skaafrica.atlassian.net/browse/SR-1962).
=> Support katstore64 API

scripts/mvf_rechunk.py
=> Fix mvf_rechunk script

katdal/lazy_indexer.py
dask_getitem is used for both first- and second-stage indexing in
DaskLazyIndexer. When first-stage indexing keeps all (no `select`) or
most (e.g. `scans=track`) of the data, the culling is not particularly
useful, very slow, and might be harmful as it throws away the
highlevelgraph structure. So only apply it when the number of blocks is
reduced by at least 50%.
Also ensure that the replacement graph is a HighLevelGraph - dask
doesn't currently do it automatically, unlike the da.Array constructor.
=> Only apply culling optimisation when selecting a small slice

katdal/applycal.py
CategoricalData already has a convenient way to get all the unique
values :-)
=> Optimise set(targets) -> targets.unique_values

scripts/mvf_rechunk.py
The alias streams like spectral_image.sdp_l0 didn't work because:
- The regex didn't allow for a dot in the stream name;
- The code to determine stream type didn't cater for stream inheritance.
=> mvf_rechunk: support imaging streams

NEWS.rst, katdal/__init__.py
This updates the changelog, which will get merged back into master. The final commit will be tagged as v0.15 and released.
=> Release v0.15

setup.py
It needs support for `key_type`.
=> Require at least katsdptelstate 0.10

katdal/sensordata.py, katdal/test/test_sensordata.py
This allows adjustment of the timestamps of any sensor, by adding a custom per-sensor time offset.
=> New 'time_offset' sensor property

NEWS.rst
Last Python 2 release... To be merged into `python2` branch.
=> Update changelog for v0.16 release

katdal/test/test_datasources.py
It's not used internally by katdal, but I'm using it in katsdpimager to
check that it handles unusual bls_ordering.
=> Add bls_ordering_override option to make_fake_data_source

katdal/lazy_indexer.py
This mirrors ska-sa/katsdpimager#87.
=> Point at newer open Dask bug to explain workaround

pyproject.toml, requirements.txt, test-requirements.txt
- Remove recursive dependencies
- Add -c options to pin the recursive dependencies
- Add a pyproject.toml to ensure katversion is available during setup
See SPR1-833.
=> Refactor requirement files

katdal/ms_extra.py
Fixes SIGMA_SPECTRUM, WEIGHT and SIGMA column issues as discussed.
=> Populate SIGMA_SPECTRUM and redo SIGMA and WEIGHT

katdal/ms_async.py, katdal/ms_extra.py, scripts/mvftoms.py
When a MVF to MS conversion happens the connection might drop which leads to a half written MS file. This change
adds functionality to detect how many rows have been written to the MS file and continues after that number of frames.
=> SPR1-1312: Continue MS conversion on interrupt

NEWS.rst
=> SPR1-3017: Prepare for v0.22

katdal/dataset.py, katdal/test/test_dataset.py, scripts/mvftoms.py
This is an attempt to resurrect PR #341. I've addressed all my own comments in the old PR. :-)
This does not yet do negation, but that needs a whole new PR (see SPR1-1323).
=> SPR1-1155: Select targets by their tags
